# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mzyy94.com
baseurl: ""
title: 犬アイコンのみっきー
title_separator          : "-"
subtitle:
description: いろいろ書く。
name: &id mzyy94
repository: mzyy94/mzyy94.github.io
logo: /assets/images/logo.png

remote_theme: mmistakes/so-simple-theme@3.2.0

# ----------------------- #
#          Author         #
# ----------------------- #

author:
  name             : "mzyy94"
  fullname         : "Yuki MIZUNO"
  picture          : /assets/images/logo.png
  bio              : 何かしら生きた証を遺したい (575)
  location         : Tokyo
  twitter          : mzyy94
  links:
  - title: "Website"
    icon: "fas fa-fw fa-link"
    url: https://mzyy94.com
  - title: "Keybase"
    icon: "fab fa-fw fa-keybase"
    url: https://keybase.io/mzyy94
  - title: "Twitter"
    icon: "fab fa-fw fa-twitter"
    url: https://twitter.com/mzyy94
  - title: "Bitbucket"
    icon: "fab fa-fw fa-bitbucket"
    url: https://bitbucket.org/mzyy94
  - title: "GitHub"
    icon: "fab fa-fw fa-github"
    url: https://github.com/mzyy94
  - title: "GitLab"
    icon: "fab fa-fw fa-gitlab"
    url: https://gitlab.com/mzyy94
  - title: "Foursquare"
    icon: "fab fa-fw fa-foursquare"
    url: https://foursquare.com/mzyy94
  - title: "Steam"
    icon: "fab fa-fw fa-steam"
    url: https://steamcommunity.com/id/RockingUniform
  - title: "SlideShare"
    icon: "fab fa-fw fa-slideshare"
    url: https://www.slideshare.net/mzyy94
  - title: "Twitch"
    icon: "fab fa-fw fa-twitch"
    url: https://www.twitch.tv/mzyy94
  - title: "Wishlist"
    icon: "fab fa-fw fa-amazon"
    url: https://amzn.mzyy94.com
  - title: "PayPal"
    icon: "fab fa-fw fa-paypal"
    url: https://www.paypal.me/mzyy94
  - title: "Public keys"
    icon: "fas fa-fw fa-key"
    url: https://github.com/mzyy94.keys



# ----------------------- #
#     Link & Markdown     #
# ----------------------- #

baseurl: ""
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
relative_links:
  enabled:     true
  collections: true
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
  syntax_highlighter: rouge
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  footnote_nr:    1
highlighter: rouge
lsi: false
breadcrumbs: true

# ----------------------- #
#           Sass          #
# ----------------------- #

sass:
  style: compressed

# ----------------------- #
#    Paginate & Excerpt   #
# ----------------------- #

paginate: 10
paginate_path: "/blog/page:num"
excerpt_link: "Read more"
excerpt_separator: "<!-- more -->"
recent_posts: 5
read_time: true

# ----------------------- #
#      Locale & Date      #
# ----------------------- #

lang: ja
locale: ja-JP
date_format: "%Y-%m-%d"
timezone: Asia/Tokyo

# ----------------------- #
#  RSS & Search & Comment #
# ----------------------- #

footer_links:
  - title: Feed
    url: /blog/atom.xml
    icon: fas fa-rss-square

search_full_content: false

feed:
  path: /blog/atom.xml
  excerpt_only: true
  posts_limit: 20

disqus:
  shortname: mzyy94blog

# ----------------------- #
#        Generate         #
# ----------------------- #

exclude:
  - README.md
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

compress_html:
  clippings: all
  ignore:
    envs: development

# ----------------------- #
#        Defaults         #
# ----------------------- #
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      author_profile: true

# ----------------------- #
#        SNS Share        #
# ----------------------- #

twitter:
  username: *id
# Mentions
jekyll-mentions: https://twitter.com

# ----------------------- #
#    Analytics & SEO      #
# ----------------------- #

google_analytics: UA-41944495-3
google_site_verification: m5HDLtvpHciiq97KscNByMXhvFiwvwJzlwBHEDUlmwk

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
plugins:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji


# ----------------------- #
#         Archives        #
# ----------------------- #
category_archive_path: "/blog/categories/#"
tag_archive_path: "/blog/tags/#"

# ----------------------- #
#           gist          #
# ----------------------- #
gist:
  noscript: false